# 定义两个矩阵并计算其逐元素相加

In [9]:
A = [[1, 2, 3],
    [4, 5, 6]]
A

[[1, 2, 3], [4, 5, 6]]

In [15]:
B = [[1, 0, 0],
    [0, 1, 0]]
B

[[1, 0, 0], [0, 1, 0]]

# 逐元素相加矩阵A和矩阵B

In [43]:
A_plus_B = [[A[i][j] + B[i][j]# 计算矩阵A和B中对应元素的和
            for j in range(len(A[0]))]# 遍历矩阵列
            for i in range(len(A))]# 遍历矩阵行

In [48]:
print(A_plus_B)# 输出矩阵A和B逐元素相加的结果

[[2, 2, 3], [4, 6, 6]]


# 使用numpy对两个矩阵进行逐元素相加

In [56]:
import numpy as np

In [60]:
A = [[1, 2, 3],
    [4, 5, 6]]

In [63]:
B = [[1, 0, 0],
    [0, 1, 0]]

# 使用numpy的数组相加方法对矩阵A和矩阵B逐元素相加

In [79]:
print(np.array(A) + np.array(B))# 将A和B转换为numpy数组并逐元素相加

[[2 2 3]
 [4 6 6]]


# 使用numpy的add函数对矩阵A和矩阵B逐元素相加

In [76]:
print(np.add(A, B))# 使用numpy的add函数逐元素相加并输出结果

[[2 2 3]
 [4 6 6]]
