# 转置行向量和列向量的操作

In [6]:
import numpy as np

## 定义一个行向量并转置为列向量

In [15]:
a_row = np.array([[1,2,3]]) # 定义一个行向量
a_row

array([[1, 2, 3]])

In [19]:
b = a_row.T
b

array([[1],
       [2],
       [3]])

## 定义一个列向量并转置为行向量

In [25]:
b_col = np.array([[1],[2],[3]])
b_col

array([[1],
       [2],
       [3]])

In [29]:
a = b_col.T
a

array([[1, 2, 3]])