In [3]:
import numpy as np

# 行向量点积

In [11]:
a_row = np.array([[1, 2, 3]])


In [14]:
b_row = np.array([[4, 3, 2]])

In [20]:
a_dot_b = np.inner(a_row, b_row)
print(a_dot_b)

[[16]]


In [26]:
print(np.inner(a_row[:], b_row[:]))

[[16]]


In [33]:
print(np.sum(a_row * b_row))

16


# 列向量点积

In [41]:
a_col = np.array([[1], [2], [3]])
b_col = np.array([[-1], [0], [1]])

In [45]:
a_col.T @ b_col

array([[2]])

In [49]:
print(np.sum(a_col * b_col))

2


# 向量张量积

In [59]:
a_dot_b = np.inner(a_col, b_col)

In [63]:
print(a_dot_b)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [67]:
a_col @ b_col.T

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])