# 定义并操作列向量

In [5]:
import numpy as np

In [10]:
a_col = np.array([[1], [2], [3]])
a_col

array([[1],
       [2],
       [3]])

In [16]:
b_col = 2 * a_col
b_col

array([[2],
       [4],
       [6]])

# 定义并操作行向量

In [24]:
a_row = np.array([[1, 2, 3]])
a_row

array([[1, 2, 3]])

In [27]:
b_row = 2 * a_row
b_row

array([[2, 4, 6]])

# 定义并操作矩阵

In [35]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
B = 2 * A
B

array([[ 2,  4,  6],
       [ 8, 10, 12]])