# 定义矩阵并计算矩阵乘积

In [10]:
import numpy as np

A = np.array([[1, 2],
             [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [14]:
B = np.array([[4, 2],
            [3, 1]])
B

array([[4, 2],
       [3, 1]])

In [19]:
c = A @ B
c

array([[10,  4],
       [24, 10]])

# 逐元素计算矩阵乘法的结果

In [ ]:
A[[0]] @ B[:, [0]]