# 行向量的逐元素乘积

In [4]:
import numpy as np

In [12]:
a = np.array([[1, 2, 3]])
a

array([[1, 2, 3]])

In [16]:
b = np.array([[4, 5, 6]])
b

array([[4, 5, 6]])

In [20]:
a_times_b = a * b
a_times_b

array([[ 4, 10, 18]])

# 矩阵的逐元素乘积

In [27]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
B = np.array([[1, 2, 3],
             [-1, 0, 1]])
B

array([[ 1,  2,  3],
       [-1,  0,  1]])

In [36]:
A_times_B = A * B
A_times_B

array([[ 1,  4,  9],
       [-4,  0,  6]])